name: Test CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
    steps:
      -
        name: Set FIREBASE_CREDENTIALS environment variable
        run: echo "FIREBASE_CREDENTIALS=$(echo ${{ secrets.FIREBASE_CREDENTIALS }})" >> $GITHUB_ENV
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Install requirements
        run: pip install -r requirements.txt
      -
        name: Run tests
        run: cd src && pytest test.py --cov main --cov-report xml:../coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
            auto_fix: true
            black: true
            black_auto_fix: true
